# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_manage', '0003_auto_20170721_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectInfo',
            fields=[
                ('projectname', models.CharField(max_length=32)),
                ('appid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=64)),
                ('createdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('deleteflag', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='userList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('deleteflag', models.CharField(max_length=1)),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_manage.projectInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_manage.userInfo')),
            ],
        ),
    ]
