# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_manage', '0005_auto_20170726_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mailaddress',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
