# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_manage', '0006_auto_20170726_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='appid',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='roleid',
            new_name='roleinfo',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='uid',
            new_name='user',
        ),
    ]
