# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_manage', '0007_auto_20170727_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='ability',
            field=models.IntegerField(null=True),
        ),
    ]
