# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_manage', '0008_auto_20170728_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat_manage.projectInfo'),
        ),
    ]
